"use client";

import { useState } from "react";

interface Asset {
  id: string;
  storage_url: string;
  context_note: string | null;
  quality_score: number | null;
  context_auto_generated: boolean;
  detected_vendors: string[];
}

export function ContextReview({
  siteId,
  initialAssets,
}: {
  siteId: string;
  initialAssets: Asset[];
}) {
  const [assets, setAssets] = useState(initialAssets);
  const [isOpen, setIsOpen] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [editNote, setEditNote] = useState("");
  const [saving, setSaving] = useState(false);

  const autoGenerated = assets.filter((a) => a.context_auto_generated);
  const manual = assets.filter((a) => !a.context_auto_generated && a.context_note);
  const untagged = assets.filter((a) => !a.context_note);

  async function saveNote(assetId: string) {
    setSaving(true);
    try {
      await fetch(`/api/assets/${assetId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ context_note: editNote }),
      });
      setAssets((prev) =>
        prev.map((a) => (a.id === assetId ? { ...a, context_note: editNote } : a))
      );
      setEditing(null);
    } catch {
      alert("Save failed");
    } finally {
      setSaving(false);
    }
  }

  function startEdit(asset: Asset) {
    setEditing(asset.id);
    setEditNote(asset.context_note || "");
  }

  return (
    <div className="mt-3">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 text-xs font-medium text-accent hover:underline"
      >
        {isOpen ? "▾" : "▸"} Context Notes
        <span className="text-muted">
          ({autoGenerated.length} auto / {manual.length} manual / {untagged.length} untagged)
        </span>
      </button>

      {isOpen && (
        <div className="mt-2 rounded border border-border bg-background p-3">
          {/* Auto-generated — needs review */}
          {autoGenerated.length > 0 && (
            <div className="mb-4">
              <h4 className="mb-2 text-[10px] font-medium text-warning">
                Auto-generated — review for accuracy ({autoGenerated.length})
              </h4>
              <div className="space-y-2">
                {autoGenerated.map((asset) => (
                  <div key={asset.id} className="flex gap-3 border-b border-border pb-2 last:border-0">
                    <img
                      src={asset.storage_url}
                      alt=""
                      className="h-16 w-16 shrink-0 rounded object-cover"
                    />
                    <div className="min-w-0 flex-1">
                      {editing === asset.id ? (
                        <div className="flex gap-2">
                          <input
                            value={editNote}
                            onChange={(e) => setEditNote(e.target.value)}
                            onKeyDown={(e) => e.key === "Enter" && saveNote(asset.id)}
                            className="flex-1 text-[10px]"
                            autoFocus
                          />
                          <button
                            onClick={() => saveNote(asset.id)}
                            disabled={saving}
                            className="text-[10px] text-accent hover:underline"
                          >
                            Save
                          </button>
                          <button
                            onClick={() => setEditing(null)}
                            className="text-[10px] text-muted"
                          >
                            Cancel
                          </button>
                        </div>
                      ) : (
                        <div className="flex items-start justify-between">
                          <div>
                            <p className="text-[10px]">{asset.context_note}</p>
                            {asset.detected_vendors.length > 0 && (
                              <p className="mt-0.5 text-[9px] text-accent">
                                Vendors: {asset.detected_vendors.join(", ")}
                              </p>
                            )}
                          </div>
                          <button
                            onClick={() => startEdit(asset)}
                            className="ml-2 shrink-0 text-[10px] text-muted hover:text-foreground"
                          >
                            Edit
                          </button>
                        </div>
                      )}
                      <p className="mt-0.5 text-[9px] text-muted">
                        q: {((Number(asset.quality_score) || 0) * 100).toFixed(0)}%
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Untagged — no context note at all */}
          {untagged.length > 0 && (
            <div className="mb-4">
              <h4 className="mb-2 text-[10px] font-medium text-danger">
                No context note ({untagged.length})
              </h4>
              <div className="flex flex-wrap gap-2">
                {untagged.slice(0, 20).map((asset) => (
                  <div key={asset.id} className="relative">
                    <img
                      src={asset.storage_url}
                      alt=""
                      className="h-12 w-12 rounded object-cover opacity-60"
                    />
                    <span className="absolute bottom-0 right-0 rounded-tl bg-background px-1 text-[8px] text-muted">
                      {((Number(asset.quality_score) || 0) * 100).toFixed(0)}%
                    </span>
                  </div>
                ))}
                {untagged.length > 20 && (
                  <span className="flex h-12 w-12 items-center justify-center text-[10px] text-muted">
                    +{untagged.length - 20}
                  </span>
                )}
              </div>
            </div>
          )}

          {/* Manual — subscriber tagged these */}
          {manual.length > 0 && (
            <div>
              <h4 className="mb-2 text-[10px] font-medium text-success">
                Manually tagged ({manual.length})
              </h4>
              <div className="space-y-1">
                {manual.slice(0, 10).map((asset) => (
                  <div key={asset.id} className="flex items-center gap-2">
                    <img src={asset.storage_url} alt="" className="h-8 w-8 rounded object-cover" />
                    <p className="truncate text-[10px]">{asset.context_note}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
