name = "tracpost-blog-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Routes — Worker intercepts on both blogs.tracpost.com and custom hostnames
routes = [
  { pattern = "blogs.tracpost.com/*", zone_name = "tracpost.com" },
  { pattern = "blog.b2construct.com/*", zone_name = "tracpost.com" }
]
